Repository ConducereIT/lsebucuresti.org, pull requests merged in 2023-09, with the labels that each got.

#5 add footer ev
  client/src/views/Evenimente.view.js
Labels: READY TO MERGE, bug fix

#8 style
  client/src/App.css
  client/src/App.js
  client/src/assets/img/LogoWhite.png
  client/src/assets/img/LogoWhite.webp
  client/src/assets/img/LseBanner.png
  client/src/assets/img/LseBanner.webp
  client/src/components/AboutFaq.component.js
  client/src/components/Banner.component.js
  client/src/components/Footer.component.js
  client/src/components/Header.component.js
  client/src/components/Preloader.component.js
  client/src/components/Stats.component.js
  client/src/views/Home.view.js
Labels: READY TO MERGE

#9 small changes
  client/src/assets/config/configFacultate.js
  client/src/assets/img/Facultate/profesori/CarmenFlorea.webp
  client/src/assets/img/Facultate/profesori/Nastac.webp
  client/src/assets/img/Facultate/profesori/Rodica-Constantinescu.webp
  client/src/assets/img/Facultate/profesori/avatar.webp
  client/src/assets/img/Facultate/profesori/hobincu.webp
  client/src/assets/img/Facultate/profesori/laura_florea.webp
  client/src/assets/img/Facultate/profesori/mihai_stanciu.webp
  client/src/assets/img/Facultate/profesori/mihnea_udrea.webp
  client/src/assets/img/cover/cinesuntem.webp
  client/src/assets/img/cover/structura.webp
  client/src/assets/img/cover/viziune.webp
  client/src/components/About.component.js
  client/src/components/Footer.component.js
  client/src/components/Header.component.js
  client/src/components/Membrii.component.js
  client/src/views/Echipa.view.js
  client/src/views/Facultate.view.js
Labels: READY TO MERGE

#11 2 new components and some fixd
  client/src/components/Contact.component.js
  client/src/components/Departamente/Descriere.component.js
  client/src/components/Departamente/Item.component.js
  client/src/components/Departamente/List.component.js
  client/src/components/Footer.component.js
  client/src/views/Departamente.view.js
Labels: component update, page update
